---
# Provision Web Server
- name: Provision Web Server Role
  local_action: 
    module: ec2
    id: "{{ webserver_tag_name }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    instance_tags: '{"Name":"{{webserver_tag_name}}", "Type":"{{webserver_tag_type}}"'
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    count: "{{ count }}"    
  register: ec2

 - debug: var=item
   with_items: ec2.instances

 - add_host:
     name: "{{ item.public_ip }}"
     groups: "{{ webserver_tag_type }}"
     ec2_region: "{{ region }}"
     ec2_tag_Name: "{{ webserver_tag_name }}"
     ec2_ip_address: "{{ item.public_ip }}"
   with_items: ec2.instances

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=5 timeout=320 state=started
   with_items: ec2.instances